GHA: Attempt to coverage job

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -1,25 +1,25 @@
 on: [push]
 
-name: covr
+name: test-coverage.yaml
 
 permissions: read-all
 
 jobs:
-  covr:
-    if: "! contains(github.event.head_commit.message, '[ci skip]')"
-
-    timeout-minutes: 20
-
+  test-coverage:
     runs-on: ubuntu-latest
-    
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
     steps:
       - uses: actions/checkout@v4
 
-      - uses: r-lib/actions/setup-pandoc@v2
-      
+      - name: Assert CODECOV_TOKEN is set
+        run: |
+          if [[ -z "${{secrets.CODECOV_TOKEN}}" ]]; then
+            >&2 echo "::error::ERROR: 'secrets.CODECOV_TOKEN' not set"
+            exit 1
+          fi
+
       - uses: r-lib/actions/setup-r@v2
         with:
           use-public-rspm: true
@@ -29,11 +29,6 @@ jobs:
           extra-packages: any::covr, any::xml2
           needs: coverage
 
-      - name: Install dependencies
-        run: |
-          install.packages(".", repos=NULL, type="source")
-        shell: Rscript {0}
-
       - name: Test coverage
         run: |
           cov <- covr::package_coverage(
@@ -41,6 +36,7 @@ jobs:
             clean = FALSE,
             install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package")
           )
+          print(cov)
           covr::to_cobertura(cov)
         shell: Rscript {0}
 
@@ -51,13 +47,6 @@ jobs:
           plugin: noop
           disable_search: true
           token: ${{ secrets.CODECOV_TOKEN }}
-
-      - name: Show testthat output
-        if: always()
-        run: |
-          ## --------------------------------------------------------------------
-          find '${{ runner.temp }}/package' -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
 
       - name: Upload test results
         if: failure()
